# Generated by Django 5.1.3 on 2024-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_epic_sprint_alter_task_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
